language: php
php:
  - '7.0'
  - '7.1'
  - '7.2'
install:
  - composer install
  - npm install
  - php scripts/setup.php --application_url=http://localhost
  - php artisan key:generate
script: vendor/bin/phpunit tests
